name: Python Test Automation

on: 
  push:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment

jobs:
  Unit-test: 
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        env:
          TARGET_VAR: ${{ inputs.target-env }}
          DEV_VALUE_A: ${{ vars.DEV_VALUE_A }}
          DEV_VALUE_B: ${{ vars.DEV_VALUE_B }}
        run: |
          echo "Environment is $TARGET_VAR"

          if [ "$TARGET_VAR" = "dev" ]; then
            echo "I am in the dev branch"
            DEV_RESULT=$((DEV_VALUE_A + DEV_VALUE_B))
            echo "Dev Branch result is $DEV_RESULT"

          elif [ "$TARGET_VAR" = "stage" ]; then
            echo "I am in the stage branch"
            STAGE_RESULT=$((STAGE_VALUE_A + STAGE_VALUE_B))
            echo "STAGE Branch result is $STAGE_RESULT"

          elif [ "$TARGET_VAR" = "prod" ]; then
            echo "I am in the production branch"
            PROD_RESULT=$((PROD_VALUE_A + PROD_VALUE_B))
            echo "Dev Branch result is $PROD_RESULT"

          else
            echo "Unknown environment: $TARGET_VAR"
          fi
