name: Python Test Automation 

on: 
  push:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment

jobs:
  Unit-test: 
    runs-on: ubuntu-latest
    environment: ${{inputs.target-env}}
    steps: 
      - name: environment vars 
        run: |
          echo "Environment is ${{vars.TARGET_VAR}}"
          if [ ${{vars.TARGET_VAR}} == "dev" ]; then 
            echo "I am in dev branch" 
            env:
              DEV_RESULT=$((DEV_VALUE_A + DEV_VALUE_B))
              echo "Dev Branch result is $DEV_RESULT"
          elif [ ${{vars.TARGET_VAR}} == "stage" ]; then 
            echo "I am in stage branch" 
          elif [ ${{vars.TARGET_VAR}} == "prod" ]; then 
            echo "I am in production branch" 
          else 
            echo "Unknown environment: {{vars.TARGET_VAR}}"
          fi
            
            

name: Python Test Automation

on: 
  push:
  workflow_dispatch:
    inputs:
      target-env:
        description: "Target environment (dev, stage, prod)"
        required: true
        type: string

jobs:
  Unit-test: 
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    steps: 
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Environment Variables
      - name: Set Environment Variables
        env:
          DEV_VALUE_A: ${{ vars.DEV_VALUE_A }}
          DEV_VALUE_B: ${{ vars.DEV_VALUE_B }}
          TARGET_ENV: ${{ inputs.target-env }}
        run: |
          echo "Environment is $TARGET_ENV"
          
          if [ "$TARGET_ENV" = "dev" ]; then 
            echo "I am in the dev branch"
            DEV_RESULT=$((DEV_VALUE_A + DEV_VALUE_B))
            echo "Dev Branch result is $DEV_RESULT"

          elif [ "$TARGET_ENV" = "stage" ]; then 
            echo "I am in the stage branch"

          elif [ "$TARGET_ENV" = "prod" ]; then 
            echo "I am in the production branch"

          else 
            echo "Unknown environment: $TARGET_ENV"
          fi
