name: Python Test Automation 

on: 
  push:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment

jobs:
  Unit-test: 
    runs-on: ubuntu-latest
    environment: ${{inputs.target-env}}
    steps: 
      - name: environment vars 
        run: |
          echo "Environment is ${{vars.TARGET_VAR}}"
          if [ ${{vars.TARGET_VAR}} == "dev" ]; then 
            echo "I am in dev branch" 
            
          elif [ ${{vars.TARGET_VAR}} == "stage" ]; then 
            echo "I am in stage branch" 
          elif [ ${{vars.TARGET_VAR}} == "prod" ]; then 
            echo "I am in production branch" 
          else 
            echo "Unknown environment: {{vars.TARGET_VAR}}"
          fi
            
            

      
