name: Python Test Automation 

on: 
  push:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment

jobs:
  Unit-test: 
    runs-on: ubuntu-latest
    environment: ${{inputs.target-env}}
    steps: 
      - name: environment vars 
        run: |
          echo "Environment is ${{vars.TARGET_VAR}}"
    
      
